services:
  mysql-server:
    container_name: "mysql-server"
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_mysql-server
    env_file:
      - ./containers/mysql-server/.env
    volumes:
      - "./containers/mysql-server/:/app/"
      - "./library/mysql-server:/project:ro"
    working_dir: /app
    command: "/bin/sh -c 'pymon main.py'"
    depends_on:
      rabbitmq:
        condition: service_healthy
