FROM python:3.12.2-slim

ARG USERNAME=agno
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID $USERNAME && \
    useradd -m -u $USER_UID -g $USER_GID $USERNAME

WORKDIR /app

COPY ./discussion-room .

RUN pip install --no-cache-dir -r requirements.txt

USER $USERNAME
